![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

#### "Las Top 100 universidades del mundo"

In [ ]:
#Escribe el título del proyecto en Markdown
titulo = "Las Top 100 universidades del mundo"

### TEMA

#### "Qué factores afectan a que una universidad sea mejor que otra y conseguir un ranking institucional más elevado que sus competidoras"

In [ ]:
# Describe brevemente el tema del proyecto en Markdown
tema = "Qué factores afectan a que una universidad sea mejor que otra y conseguir un ranking institucional más elevado que sus competidoras"

In [ ]:
# ALTERNATIVA: 
# titulo = "Qué nos dicen los resultados de exámenes de los estudiantes"
# tema = "Qué factores afectan a la hora de sacar una mejor nota"

### HIPÓTESIS

Define aquí lo que será la hipótesis de tu proyecto.
Deberás tener más de una, pero tu proyecto lo harás teniendo una principal hipótesis.

#### HIPÓTESIS PRINCIPAL: "Las universidades privadas no son mejores que las públicas"

In [ ]:
# Escribe tu hipótesis principal en Markdown
hipotesis_1 = "Las universidades privadas no son mejores que las públicas"

#### HIPÓTESIS 2: "La mayoría de las mejores universidades están en EEUU y son las que más estudiantes han tenido a lo largo de su historia"
#### HIPÓTESIS 3: "Contra más programas se ofrezcan en la universidad, hay más personal docente"
#### HIPÓTESIS 4: "Contra más campuses tenga una universidad, más área tiene"

In [ ]:
# Escribe más hipótesis si las hubiera en Markdown
# hipotesis_2 = "La mayoría de las mejores universidades están en EEUU y son las que más estudiantes han tenido a lo largo de su historia"
# hipotesis_3 = "Contra más programas se ofrezcan en la universidad, hay más personal docente"
# hipotesis_4 = "Contra más campuses tenga una universidad, más área tiene"
# ...

In [ ]:
# ALTERNATIVA: 
# hipotesis_principal = "Los estudiantes con una buena organización de estudio tienen más probabilidades de sacar mejor nota" 
# Se tienen en cuenta columnas como Attendence, Hours_Studied, Sleep_Hours y Access_to_Resources	

# subhipotesis_1 = "La importancia de la motivación de un estudiante a la hora de la nota final"
# Se tiene en cuenta la columna "Motivation_Level"

# subhipotesis_2 = "El entorno en el que ha crecido el estudiante no afecta tanto en el rendimiento de los exámenes"
# Se tienen en cuenta columnas como Family_Income, Teacher_Quality, School_Type y Parental_Education_Level

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [1]:
import pandas as pd

In [ ]:
# guarda en variables los datasets y su fuente
# df_1 = pd.DataFrame()
# fuente_1 = ""
# df_2 = pd.DataFrame()
# fuente_2 = ""
# df_3 = pd.DataFrame()
# fuente_3 = ""
# df_4 = pd.DataFrame()
# fuente_4 = ""
# df_5 = pd.DataFrame()
# fuente_5 = ""
# ...

dataset = pd.read_csv(r"C:\Users\data_\.cache\kagglehub\datasets\syedaeman2212\top-100-universities\versions\1\top_100_universities_dataset.csv")
dataset
#fuente= "Kaggle" https://www.kaggle.com/datasets/syedaeman2212/top-100-universities/data

#La columna "Location" está mal. Habrá que arreglarlo
#La columna "Total_Faculty" se refiere al staff total que hay en esa universidad
#En la última columna "Acres" significa la medida de superficie del campus en el sistema de medición estadounidense

,Position,University_Name,Location,Established_Year,Total_Students,Number_of_Campuses,Programs_Offered,University_Type,Total_Faculty,Campus_Area_Acres
0,1,University of Oxford,"Cambridge, Switzerland",1250,19628,3,427,Public,5843,6167
1,2,Columbia University,"Stanford, China",1432,7082,1,97,Public,2205,4239
2,3,University of Michigan,"Cambridge, China",1203,51925,11,409,Private,2105,3779
3,4,University of Edinburgh,"Singapore, USA",1777,57810,3,407,Private,3087,2376
4,5,University of Cambridge,"London, Switzerland",1104,11078,7,99,Private,7242,2917
...,...,...,...,...,...,...,...,...,...,...
95,96,Yale University,"Singapore, Switzerland",1257,20108,2,419,Public,2884,1079
96,97,Columbia University,"Ann Arbor, UK",1196,19180,12,297,Private,6235,4929
97,98,Peking University,"Edinburgh, Switzerland",1102,59567,4,201,Public,3256,1569
98,99,UCL,"Cambridge, China",1129,22977,1,77,Private,6013,7833
99,100,University of Cambridge,"New York, Singapore",1105,5803,10,195,Private,4221,3708

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [3]:
# Primer dataset
dataset.head()

,Position,University_Name,Location,Established_Year,Total_Students,Number_of_Campuses,Programs_Offered,University_Type,Total_Faculty,Campus_Area_Acres
0,1,University of Oxford,"Cambridge, Switzerland",1250,19628,3,427,Public,5843,6167
1,2,Columbia University,"Stanford, China",1432,7082,1,97,Public,2205,4239
2,3,University of Michigan,"Cambridge, China",1203,51925,11,409,Private,2105,3779
3,4,University of Edinburgh,"Singapore, USA",1777,57810,3,407,Private,3087,2376
4,5,University of Cambridge,"London, Switzerland",1104,11078,7,99,Private,7242,2917

In [ ]:
# ALTERNATIVA:
students = pd.read_csv(r"C:\Users\data_\.cache\kagglehub\datasets\grandmaster07\student-exam-performance-dataset-analysis\versions\1\StudentPerformanceFactors.csv")
students
#fuente= "Kaggle" https://www.kaggle.com/datasets/grandmaster07/student-exam-performance-dataset-analysis/data

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [5]:
students.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70